name: ScapeSuite
version: 0.4
main: me.tamazaki.suite.Main
description: ScapeMC Core Plugin.
depend: [PermissionsEx]

commands:
    ping:
      description: Pings a player
    list:
      description: Lists the number of players.
    ban:
      description: Bans a player.